apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: jonashiltl/notification-service
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          command:
            - air        
          ports:
            - containerPort: 8081
