apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: jonashiltl/user-service
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          command:
            - air
          ports:
            - containerPort: 8081
